name: 0xleaked

services:
  postgres:
    image: postgres:16-alpine
    container_name: 0xleaked-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: 0xleaked
    ports:
      - "15432:5432"
    volumes:
      - 0xleaked_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d 0xleaked"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: 0xleaked-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - 0xleaked_redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  0xleaked_pgdata:
  0xleaked_redisdata:
