packages:
  - "apps/*"
  - "services/*"
  - "packages/*"
  - "contracts"
allowBuilds:
  '@reown/appkit': true
  bufferutil: set this to true or false
  esbuild: true
  keccak: true
  protobufjs: true
  secp256k1: true
  unrs-resolver: true
  utf-8-validate: set this to true or false
