/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BreachRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "domainSeparator"
      | "eip712Domain"
      | "isRegistered"
      | "isVerifier"
      | "nonces"
      | "owner"
      | "recordBreachWithProof"
      | "records"
      | "recordsOfBeneficiary"
      | "renounceOwnership"
      | "setVerifier"
      | "totalBreaches"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BreachRecorded"
      | "EIP712DomainChanged"
      | "OwnershipTransferred"
      | "VerifierSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "domainSeparator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistered",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "nonces", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordBreachWithProof",
    values: [
      BytesLike,
      string,
      string,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "records",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordsOfBeneficiary",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setVerifier",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "totalBreaches",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "domainSeparator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isVerifier", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nonces", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordBreachWithProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "records", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordsOfBeneficiary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalBreaches",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace BreachRecordedEvent {
  export type InputTuple = [
    id: BigNumberish,
    targetHash: BytesLike,
    beneficiary: AddressLike,
    source: string,
    dataType: string,
    reporter: AddressLike,
    nonce: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    targetHash: string,
    beneficiary: string,
    source: string,
    dataType: string,
    reporter: string,
    nonce: bigint
  ];
  export interface OutputObject {
    id: bigint;
    targetHash: string;
    beneficiary: string;
    source: string;
    dataType: string;
    reporter: string;
    nonce: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EIP712DomainChangedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifierSetEvent {
  export type InputTuple = [verifier: AddressLike, enabled: boolean];
  export type OutputTuple = [verifier: string, enabled: boolean];
  export interface OutputObject {
    verifier: string;
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BreachRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): BreachRegistry;
  waitForDeployment(): Promise<this>;

  interface: BreachRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  domainSeparator: TypedContractMethod<[], [string], "view">;

  eip712Domain: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;

  isRegistered: TypedContractMethod<
    [targetHash: BytesLike, source: string],
    [boolean],
    "view"
  >;

  isVerifier: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  nonces: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  recordBreachWithProof: TypedContractMethod<
    [
      targetHash: BytesLike,
      source: string,
      dataType: string,
      beneficiary: AddressLike,
      nonce: BigNumberish,
      deadline: BigNumberish,
      signature: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  records: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, string, bigint] & {
        targetHash: string;
        source: string;
        dataType: string;
        beneficiary: string;
        reporter: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  recordsOfBeneficiary: TypedContractMethod<
    [beneficiary: AddressLike],
    [bigint[]],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setVerifier: TypedContractMethod<
    [verifier: AddressLike, enabled: boolean],
    [void],
    "nonpayable"
  >;

  totalBreaches: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "domainSeparator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "eip712Domain"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isRegistered"
  ): TypedContractMethod<
    [targetHash: BytesLike, source: string],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isVerifier"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "nonces"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordBreachWithProof"
  ): TypedContractMethod<
    [
      targetHash: BytesLike,
      source: string,
      dataType: string,
      beneficiary: AddressLike,
      nonce: BigNumberish,
      deadline: BigNumberish,
      signature: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "records"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, string, bigint] & {
        targetHash: string;
        source: string;
        dataType: string;
        beneficiary: string;
        reporter: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordsOfBeneficiary"
  ): TypedContractMethod<[beneficiary: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVerifier"
  ): TypedContractMethod<
    [verifier: AddressLike, enabled: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalBreaches"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "BreachRecorded"
  ): TypedContractEvent<
    BreachRecordedEvent.InputTuple,
    BreachRecordedEvent.OutputTuple,
    BreachRecordedEvent.OutputObject
  >;
  getEvent(
    key: "EIP712DomainChanged"
  ): TypedContractEvent<
    EIP712DomainChangedEvent.InputTuple,
    EIP712DomainChangedEvent.OutputTuple,
    EIP712DomainChangedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "VerifierSet"
  ): TypedContractEvent<
    VerifierSetEvent.InputTuple,
    VerifierSetEvent.OutputTuple,
    VerifierSetEvent.OutputObject
  >;

  filters: {
    "BreachRecorded(uint256,bytes32,address,string,string,address,uint256)": TypedContractEvent<
      BreachRecordedEvent.InputTuple,
      BreachRecordedEvent.OutputTuple,
      BreachRecordedEvent.OutputObject
    >;
    BreachRecorded: TypedContractEvent<
      BreachRecordedEvent.InputTuple,
      BreachRecordedEvent.OutputTuple,
      BreachRecordedEvent.OutputObject
    >;

    "EIP712DomainChanged()": TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;
    EIP712DomainChanged: TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "VerifierSet(address,bool)": TypedContractEvent<
      VerifierSetEvent.InputTuple,
      VerifierSetEvent.OutputTuple,
      VerifierSetEvent.OutputObject
    >;
    VerifierSet: TypedContractEvent<
      VerifierSetEvent.InputTuple,
      VerifierSetEvent.OutputTuple,
      VerifierSetEvent.OutputObject
    >;
  };
}
